-- Core BATON domain schema.
-- User -> PlatformConnection -> Conversation -> Message -> Baton -> (Branch, Classification, Execution)

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    timezone VARCHAR(50),
    language VARCHAR(20),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE platform_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    platform_type VARCHAR(30) NOT NULL,
    workspace_id VARCHAR(255) NOT NULL,
    workspace_name VARCHAR(255),
    access_token_encrypted TEXT NOT NULL,
    refresh_token_encrypted TEXT,
    token_expires_at TIMESTAMP,
    connection_status VARCHAR(30) NOT NULL,
    last_synced_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_platform_connections_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_platform_connections_user_platform_workspace UNIQUE (user_id, platform_type, workspace_id)
);

CREATE INDEX idx_platform_connections_user_id ON platform_connections (user_id);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_connection_id BIGINT NOT NULL,
    external_conversation_id VARCHAR(255) NOT NULL,
    external_thread_id VARCHAR(255),
    conversation_type VARCHAR(30) NOT NULL,
    title VARCHAR(255),
    counterpart_external_id VARCHAR(255),
    counterpart_name VARCHAR(100),
    counterpart_timezone VARCHAR(50),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_conversations_platform_connection FOREIGN KEY (platform_connection_id) REFERENCES platform_connections (id) ON DELETE CASCADE
);

CREATE INDEX idx_conversations_platform_connection_id ON conversations (platform_connection_id);
-- external_thread_id is nullable; ''-coalescing keeps channel/DM-level (no thread) conversations unique per external_conversation_id.
CREATE UNIQUE INDEX uk_conversations_external_ref ON conversations (platform_connection_id, external_conversation_id, COALESCE(external_thread_id, ''));

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    external_message_id VARCHAR(255) NOT NULL,
    external_event_id VARCHAR(255),
    sender_external_id VARCHAR(255) NOT NULL,
    sender_type VARCHAR(30) NOT NULL,
    content TEXT NOT NULL,
    original_language VARCHAR(20),
    is_baton_generated BOOLEAN NOT NULL DEFAULT FALSE,
    sent_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
    CONSTRAINT uk_messages_conversation_external_message UNIQUE (conversation_id, external_message_id)
);

CREATE INDEX idx_messages_conversation_id ON messages (conversation_id);
-- Idempotent external event processing; not every message originates from a platform event (e.g. BATON-generated sends).
CREATE UNIQUE INDEX uk_messages_external_event_id ON messages (external_event_id) WHERE external_event_id IS NOT NULL;

CREATE TABLE batons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    trigger_message_id BIGINT NOT NULL,
    reply_message_id BIGINT,
    status VARCHAR(30) NOT NULL,
    auto_send_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMP,
    activated_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_batons_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_batons_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
    CONSTRAINT fk_batons_trigger_message FOREIGN KEY (trigger_message_id) REFERENCES messages (id) ON DELETE RESTRICT,
    CONSTRAINT fk_batons_reply_message FOREIGN KEY (reply_message_id) REFERENCES messages (id) ON DELETE SET NULL,
    -- One BATON per trigger message: at most one automated handoff per original message.
    CONSTRAINT uk_batons_trigger_message UNIQUE (trigger_message_id)
);

CREATE INDEX idx_batons_user_id ON batons (user_id);
CREATE INDEX idx_batons_conversation_id ON batons (conversation_id);
CREATE INDEX idx_batons_status ON batons (status);

CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baton_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    condition_text TEXT NOT NULL,
    condition_rule_json JSONB,
    decision_text TEXT NOT NULL,
    response_text TEXT,
    action_type VARCHAR(30) NOT NULL,
    action_config_json JSONB,
    execution_mode VARCHAR(30) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_branches_baton FOREIGN KEY (baton_id) REFERENCES batons (id) ON DELETE CASCADE
);

CREATE INDEX idx_branches_baton_id ON branches (baton_id);

CREATE TABLE classifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baton_id BIGINT NOT NULL,
    reply_message_id BIGINT NOT NULL,
    selected_branch_id BIGINT,
    confidence DECIMAL(5, 4),
    is_ambiguous BOOLEAN NOT NULL DEFAULT FALSE,
    contains_new_question BOOLEAN NOT NULL DEFAULT FALSE,
    extracted_data_json JSONB,
    reasoning_summary TEXT,
    result_status VARCHAR(30) NOT NULL,
    model_name VARCHAR(100),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_classifications_baton FOREIGN KEY (baton_id) REFERENCES batons (id) ON DELETE CASCADE,
    CONSTRAINT fk_classifications_reply_message FOREIGN KEY (reply_message_id) REFERENCES messages (id) ON DELETE RESTRICT,
    CONSTRAINT fk_classifications_selected_branch FOREIGN KEY (selected_branch_id) REFERENCES branches (id) ON DELETE SET NULL
);

CREATE INDEX idx_classifications_baton_id ON classifications (baton_id);
CREATE INDEX idx_classifications_reply_message_id ON classifications (reply_message_id);

CREATE TABLE executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baton_id BIGINT NOT NULL,
    branch_id BIGINT,
    classification_id BIGINT,
    action_type VARCHAR(30) NOT NULL,
    execution_status VARCHAR(30) NOT NULL,
    result_message_id BIGINT,
    executed_at TIMESTAMP,
    failure_reason TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_executions_baton FOREIGN KEY (baton_id) REFERENCES batons (id) ON DELETE CASCADE,
    CONSTRAINT fk_executions_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE SET NULL,
    CONSTRAINT fk_executions_classification FOREIGN KEY (classification_id) REFERENCES classifications (id) ON DELETE SET NULL,
    CONSTRAINT fk_executions_result_message FOREIGN KEY (result_message_id) REFERENCES messages (id) ON DELETE SET NULL
);

CREATE INDEX idx_executions_baton_id ON executions (baton_id);
