-- BATON Model Lab: AI eval/ops console schema.
-- Kept entirely separate from the production baton/branch/classification/execution tables per the
-- Model Lab spec — eval code must never read or write those tables.
--
-- JSON-shaped columns are stored as TEXT (not JSONB) on purpose: Model Lab's eval fixtures are
-- read/written primarily through the JPA layer via ObjectMapper, never queried with Postgres JSON
-- operators, and TEXT keeps the schema portable to the H2 (PostgreSQL-mode) runtime used by the
-- existing test suite without pulling in an extra Hibernate JSON type dependency.

ALTER TABLE users ADD COLUMN is_admin BOOLEAN NOT NULL DEFAULT FALSE;
-- MVP admin gate: no role/SSO system exists yet. Flip this flag directly in the DB for whoever
-- should have Model Lab access. See ModelLabAdminInterceptor for the enforcement point.

CREATE TABLE ai_prompt_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type VARCHAR(30) NOT NULL,
    version INT NOT NULL,
    system_prompt TEXT NOT NULL,
    developer_prompt_or_template TEXT,
    notes VARCHAR(1000),
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL,
    -- Nullable: seed fixtures (V6) are system-authored, not created via the admin API, so they carry
    -- no user id. The service layer requires a real @CurrentUserId for anything created through it.
    CONSTRAINT fk_prompt_versions_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT uk_prompt_versions_task_version UNIQUE (task_type, version)
);

CREATE INDEX idx_prompt_versions_task_type ON ai_prompt_versions (task_type);

CREATE TABLE ai_schema_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type VARCHAR(30) NOT NULL,
    version INT NOT NULL,
    json_schema TEXT NOT NULL,
    notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_schema_versions_task_version UNIQUE (task_type, version)
);

CREATE INDEX idx_schema_versions_task_type ON ai_schema_versions (task_type);

CREATE TABLE ai_model_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    task_type VARCHAR(30) NOT NULL,
    provider VARCHAR(30) NOT NULL,
    base_model VARCHAR(100) NOT NULL,
    fine_tuned_model_id VARCHAR(150),
    prompt_version_id BIGINT NOT NULL,
    schema_version_id BIGINT,
    temperature DECIMAL(3, 2) NOT NULL DEFAULT 0.20,
    confidence_threshold DECIMAL(4, 3),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_model_configs_prompt_version FOREIGN KEY (prompt_version_id) REFERENCES ai_prompt_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_model_configs_schema_version FOREIGN KEY (schema_version_id) REFERENCES ai_schema_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_model_configs_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_model_configs_task_type ON ai_model_configs (task_type);
CREATE INDEX idx_model_configs_status ON ai_model_configs (status);
-- Enforced further in ProductionModelRegistryService (needs an application-level lock around
-- promote/rollback), but a partial unique index gives a hard DB-level backstop against ever
-- persisting two PRODUCTION rows for the same task_type.
CREATE UNIQUE INDEX uk_model_configs_one_production_per_task ON ai_model_configs (task_type) WHERE status = 'PRODUCTION';

CREATE TABLE eval_datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    task_type VARCHAR(30) NOT NULL,
    version INT NOT NULL DEFAULT 1,
    description VARCHAR(1000),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_eval_datasets_task_type ON eval_datasets (task_type);

CREATE TABLE eval_scenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL,
    external_key VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    split VARCHAR(20) NOT NULL DEFAULT 'CORE',
    question TEXT NOT NULL,
    context_json TEXT,
    tags_json TEXT,
    golden_branches_json TEXT,
    notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_eval_scenarios_dataset FOREIGN KEY (dataset_id) REFERENCES eval_datasets (id) ON DELETE CASCADE,
    CONSTRAINT uk_eval_scenarios_dataset_key UNIQUE (dataset_id, external_key)
);

CREATE INDEX idx_eval_scenarios_dataset_id ON eval_scenarios (dataset_id);
CREATE INDEX idx_eval_scenarios_split ON eval_scenarios (split);

CREATE TABLE eval_reply_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL,
    reply_messages_json TEXT NOT NULL,
    expected_branch_key VARCHAR(100),
    expected_ambiguous BOOLEAN NOT NULL DEFAULT FALSE,
    expected_new_question BOOLEAN NOT NULL DEFAULT FALSE,
    expected_out_of_scope BOOLEAN NOT NULL DEFAULT FALSE,
    expected_no_match BOOLEAN NOT NULL DEFAULT FALSE,
    expected_guardrail_json TEXT,
    tags_json TEXT,
    notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_eval_reply_cases_scenario FOREIGN KEY (scenario_id) REFERENCES eval_scenarios (id) ON DELETE CASCADE
);

CREATE INDEX idx_eval_reply_cases_scenario_id ON eval_reply_cases (scenario_id);

CREATE TABLE eval_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type VARCHAR(30) NOT NULL,
    dataset_id BIGINT NOT NULL,
    split VARCHAR(20) NOT NULL,
    model_config_id BIGINT NOT NULL,
    prompt_version_id BIGINT NOT NULL,
    schema_version_id BIGINT,
    threshold_snapshot DECIMAL(4, 3),
    model_snapshot_json TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    aggregate_metrics_json TEXT,
    error_message VARCHAR(1000),
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_eval_runs_dataset FOREIGN KEY (dataset_id) REFERENCES eval_datasets (id) ON DELETE RESTRICT,
    -- model/prompt/schema versions are intentionally NOT ON DELETE CASCADE and their rows are never
    -- deleted (versioning is append-only), so a historical run's snapshot reference always resolves.
    CONSTRAINT fk_eval_runs_model_config FOREIGN KEY (model_config_id) REFERENCES ai_model_configs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_eval_runs_prompt_version FOREIGN KEY (prompt_version_id) REFERENCES ai_prompt_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_eval_runs_schema_version FOREIGN KEY (schema_version_id) REFERENCES ai_schema_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_eval_runs_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_eval_runs_dataset_id ON eval_runs (dataset_id);
CREATE INDEX idx_eval_runs_model_config_id ON eval_runs (model_config_id);
CREATE INDEX idx_eval_runs_task_type ON eval_runs (task_type);

CREATE TABLE eval_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    scenario_id BIGINT NOT NULL,
    reply_case_id BIGINT,
    input_snapshot_json TEXT NOT NULL,
    expected_json TEXT,
    actual_json TEXT,
    passed BOOLEAN NOT NULL DEFAULT FALSE,
    auto_send_expected BOOLEAN,
    auto_send_actual BOOLEAN,
    latency_ms BIGINT,
    input_tokens INT,
    output_tokens INT,
    estimated_cost DECIMAL(10, 6),
    error_message VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_eval_results_run FOREIGN KEY (run_id) REFERENCES eval_runs (id) ON DELETE CASCADE,
    CONSTRAINT fk_eval_results_scenario FOREIGN KEY (scenario_id) REFERENCES eval_scenarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_eval_results_reply_case FOREIGN KEY (reply_case_id) REFERENCES eval_reply_cases (id) ON DELETE CASCADE
);

CREATE INDEX idx_eval_results_run_id ON eval_results (run_id);
CREATE INDEX idx_eval_results_scenario_id ON eval_results (scenario_id);

CREATE TABLE generation_human_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eval_result_id BIGINT NOT NULL,
    coverage_score SMALLINT,
    separation_score SMALLINT,
    granularity_score SMALLINT,
    predecidability_score SMALLINT,
    naturalness_score SMALLINT,
    safety_score SMALLINT,
    overall_score SMALLINT,
    note VARCHAR(2000),
    reviewer_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_generation_human_reviews_result FOREIGN KEY (eval_result_id) REFERENCES eval_results (id) ON DELETE CASCADE,
    CONSTRAINT fk_generation_human_reviews_reviewer FOREIGN KEY (reviewer_id) REFERENCES users (id) ON DELETE RESTRICT,
    -- One review per result keeps the "human review, not LLM judge" workflow simple for the MVP;
    -- a reviewer edits their existing review rather than stacking duplicates.
    CONSTRAINT uk_generation_human_reviews_result UNIQUE (eval_result_id)
);

CREATE TABLE fine_tuning_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type VARCHAR(30) NOT NULL,
    provider VARCHAR(30) NOT NULL DEFAULT 'OPENAI',
    base_model VARCHAR(100) NOT NULL,
    training_dataset_id BIGINT,
    training_file_ref VARCHAR(255),
    provider_job_id VARCHAR(150),
    fine_tuned_model_id VARCHAR(150),
    status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
    metrics_json TEXT,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_fine_tuning_jobs_dataset FOREIGN KEY (training_dataset_id) REFERENCES eval_datasets (id) ON DELETE SET NULL,
    CONSTRAINT fk_fine_tuning_jobs_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX idx_fine_tuning_jobs_task_type ON fine_tuning_jobs (task_type);

CREATE TABLE model_deployment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type VARCHAR(30) NOT NULL,
    action VARCHAR(20) NOT NULL,
    from_config_id BIGINT,
    to_config_id BIGINT NOT NULL,
    performed_by BIGINT NOT NULL,
    note VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_deployment_history_from_config FOREIGN KEY (from_config_id) REFERENCES ai_model_configs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_deployment_history_to_config FOREIGN KEY (to_config_id) REFERENCES ai_model_configs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_deployment_history_performed_by FOREIGN KEY (performed_by) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX idx_deployment_history_task_type ON model_deployment_history (task_type);
